AllCops:
  TargetRubyVersion: 3.2.2

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/GlobalVars:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/LiteralAsCondition:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
